ConcurrencyPatterns.Presentation.Web/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ConcurrencyPatterns.Model.Customers;
using ConcurrencyPatterns.Presentation.Web.Models;

namespace ConcurrencyPatterns.Presentation.Web.Controllers
{
	[CookieFilter]
	public class CustomerController : BaseController
	{
		private ICustomerRepository customers;

		public CustomerController(ICustomerRepository customers)
		{
			this.customers = customers;
		}

		//
		// GET: /Customer/
		public ActionResult Index()
		{
			var customerList = customers.FindAll().ToList().OrderBy(x => x.Name);
			return View(customerList);
		}

		public PartialViewResult Create()
		{
			return PartialView();
		}

		[HttpPost]
		public ActionResult Create(CustomerViewModel customer)
		{
			CoreCreate(customer);
			return RedirectToAction("Index");
		}

		public PartialViewResult Delete(Guid id)
		{
			return PartialView(GetCustomerViewModel(id));
		}

		[HttpPost]
		public ActionResult Delete(CustomerViewModel customer)
		{
			CoreDelete(customer);
			return RedirectToAction("Index");
		}

		#region Private Methods

		private CustomerViewModel GetCustomerViewModel(Guid id)
		{
			var customer = customers.FindBy(id);
			var version = customer.Version;
			var customerViewModel = new CustomerViewModel(id, customer.Name);
			customerViewModel.Version = new VersionViewModel(version.Id, version.Value, version.ModifiedBy, version.Modified);
			return customerViewModel;
		}

		private void CoreCreate(CustomerViewModel customer)
		{
			var newCustomer = Customer.Create(customer.Name);
			customers.Add(newCustomer);
			this.ManagerContext.UnitOfWork.Commit();
		}

		private void CoreDelete(CustomerViewModel customerView)
		{
			var customer = ActivateCustomer(customerView);
			customers.Remove(customer);
			this.ManagerContext.UnitOfWork.Commit();
		}

		private Customer ActivateCustomer(CustomerViewModel customerView)
		{
			var customer = Customer.Activate(customerView.Id, customerView.Name, true);
			var version = ConcurrencyPatterns.Model.Core.Version.Activate(customerView.Version.Id, customerView.Version.Value, customerView.Version.ModifiedBy, customerView.Version.Modified);
			customer.SetSystemFields(version, DateTime.Now, UserName);
			return customer;
		}

		#endregion
	}
}

ConcurrencyPatterns.Presentation.Web/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ConcurrencyPatterns.Infrastructure.Context;
using ConcurrencyPatterns.Infrastructure.Locking;
using ConcurrencyPatterns.Model.Products;
using ConcurrencyPatterns.Presentation.Web.Models;

namespace ConcurrencyPatterns.Presentation.Web.Controllers
{
	[CookieFilter]
	public class StoreController : BaseController
	{
		private IProductRepository products;

		public StoreController(IProductRepository products)
		{
			this.products = products;
		}
		//
		// GET: /Store/
		public ActionResult Index()
		{
			var list = products.FindAll().ToList().OrderBy(x => x.Name);
			return View(list);
		}

		public ActionResult Details(Guid id)
		{
			var product = products.FindBy(id);
			return View(product);
		}

		public PartialViewResult Edit(Guid id)
		{
			return PartialView(GetProductViewModel(id));
		}

		[HttpPost]
		public ActionResult Edit(ProductViewModel product)
		{
			CoreSave(product);
			return RedirectToAction("Index");
		}

		public PartialViewResult Create()
		{
			return PartialView();
		}

		[HttpPost]
		public ActionResult Create(ProductViewModel product)
		{
			CoreCreate(product);
			return RedirectToAction("Index");
		}

		public PartialViewResult Delete(Guid id)
		{
			return PartialView(GetProductViewModel(id));
		}

		[HttpPost]
		public ActionResult Delete(ProductViewModel productViewModel)
		{
			CoreDelete(productViewModel);
			return RedirectToAction("Index");
		}

		protected override void OnException(ExceptionContext filterContext)
		{
			if (filterContext.ExceptionHandled)
				return;
			Exception e = filterContext.Exception;
			if (e is ConcurrencyException)
			{
				filterContext.ExceptionHandled = true;
				filterContext.Controller.TempData["concurrencyError"] = true;
				filterContext.Result = View("Edit");
			}
			base.OnException(filterContext);
		}

		#region Private methods (possible refactoring needed)

		private ProductViewModel GetProductViewModel(Guid id)
		{
			var product = products.FindBy(id);
			var version = product.Version;
			var productView = new ProductViewModel(product.Id, product.Name, product.Description, product.Stock);
			productView.Version = new VersionViewModel(version.Id, version.Value, version.ModifiedBy, version.Modified);
			return productView;
		}

		private Product ActivateProduct(ProductViewModel productView)
		{
			var productModel = Product.Activate(productView.Id, productView.Name, productView.Description, productView.Stock, true);
			var version = ConcurrencyPatterns.Model.Core.Version.Activate(productView.Version.Id, productView.Version.Value, productView.Version.ModifiedBy, productView.Version.Modified);
			//TODO: Date and name will change
			productModel.SetSystemFields(version, DateTime.Now, UserName);
			return productModel;
		}

		private void CoreCreate(ProductViewModel productView)
		{
			var newProduct = Product.Create(productView.Name, productView.Description, productView.Stock);
			products.Add(newProduct);
			this.ManagerContext.UnitOfWork.Commit();
		}

		private void CoreSave(ProductViewModel editedProduct)
		{
			var product = ActivateProduct(editedProduct);
			products.Save(product);
			this.ManagerContext.UnitOfWork.Commit();
		}

		private void CoreDelete(ProductViewModel deletedProduct)
		{
			var product = ActivateProduct(deletedProduct);
			products.Remove(product);
			this.ManagerContext.UnitOfWork.Commit();

		}

		#endregion
	}
}

ConcurrencyPatterns.Presentation.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>@ViewBag.Title - Concurrency Project</title>
	@Styles.Render("~/Content/css")
	@Scripts.Render("~/bundles/jquery")
	<link href="~/Content/themes/smoothness/jquery-ui.css" rel="stylesheet" />
	<script src="/Scripts/uihandling.js"></script>

	<script>
		@if (TempData["concurrencyError"] != null)
			{
				<text>
					$(document).ready(function () {
						$("#dialogError").dialog({
							modal: true
						});
					});
				</text>
			}		
	</script>

</head>

<body>
	<div class="header">
		<h1><a class="header-title header-left" href="@Url.Action("Index","Home")">Concurrency Prototype</a></h1>
		@Html.Partial("_LoginPartial")
	</div>
	<div class="body-content">
		<div class="leftMenu">
			@Html.Partial("_LeftMenu")
		</div>
		<div class="content">
			@RenderBody()
		</div>
	</div>
	<div class="footer">
		<footer>
			<p>&copy; @DateTime.Now.Year - Code Services Co.</p>
		</footer>
	</div>
	<div id="dialogError" title="Concurrency Error" style="display:none">
		<p>You cannot modify the specified product because someone else modified before your changes.</p>
		<br />
		@Html.ActionLink("Back to List", "Index")
	</div>

</body>
</html>

ConcurrencyPatterns.Presentation.Web/Views/Shared/_LeftMenu.cshtml
<ul class="leftMenuItems">
	<li>@Html.ActionLink("Home","Index","Home")</li>
	<li>@Html.ActionLink("Products", "Index", "Store")</li>
	<li>@Html.ActionLink("Customers", "Index", "Customer")</li>
</ul>